apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: stage5-apps
  namespace: tools
spec:
  generators:
    - git:
        repoURL: https://github.com/keenbytes/apps-of-apps-example
        revision: HEAD
        directories:
          - path: stage5-1-nginx
          - path: stage5-2-nginx
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: stage5
      source:
        repoURL: https://github.com/keenbytes/apps-of-apps-example
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: tools
      syncPolicy:
        automated: {}
